### ISSUE TITLE
Unnecessary deletes?

### ISSUE THREAD

**Issue by rickyvetter** [edge/react-weighted#4]
There are a lot of deletes [happening in flexify](https://github.com/edge/react-weighted/blob/master/src/flexify.js#L32-L45). I see that you're [cleaning them up](https://github.com/edge/react-weighted/blob/master/src/index.js#L16-L19) so that react-weighted related props don't get passed down to the children, but is that the only way to handle it? I'm always hesitant to mutate arguments that have been passed into my library.

**Comment by alkhe** [comment]
I was skeptical as well. I'm not exactly sure what to do either.

**Comment by alkhe** [comment]
#6 Should solve this, but it uses some es7. Should we stick with an `Object.assign`?

**Comment by alkhe** [comment]
I think es7 is fine, honestly. We're going to end up using it anyways.
